//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfClubMLD.Models.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseType()
        {
            this.GolfCourse = new HashSet<GolfCourse>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool obstcl { get; set; }
        public bool nightPly { get; set; }
        public bool cleaning { get; set; }
        public bool sprnklSys { get; set; }
        public string descr { get; set; }
        public double par { get; set; }
        public int numOfHoles { get; set; }
        public int surfc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GolfCourse> GolfCourse { get; set; }
    }
}
