//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfClubMLD.Models.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class GolfCourse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GolfCourse()
        {
            this.CourseTerm = new HashSet<CourseTerm>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string picUrl { get; set; }
        public double price { get; set; }
        public int corTypId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseTerm> CourseTerm { get; set; }
        public virtual CourseType CourseType { get; set; }
    }
}
