//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfClubMLD.Models.EFRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rent()
        {
            this.RentItems = new HashSet<RentItems>();
        }
    
        public int id { get; set; }
        public System.DateTime billDate { get; set; }
        public double totPrice { get; set; }
        public int courTrmId { get; set; }
        public int custId { get; set; }
        public System.DateTime rentDate { get; set; }
    
        public virtual CourseTerm CourseTerm { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentItems> RentItems { get; set; }
    }
}
